## Build a processed Hermann spermatogenesis SCE for velocity and fate demos.
## Output: ../data/hermann-sperm-velo.rds
##
## The full dataset is downsampled to keep the cache small. Expensive Python-backed
## velocity and CellRank steps are generated by hermann-sperm-dynamics.R.

library(sclet)
library(scRNAseq)
library(scuttle)
library(scran)
library(SingleCellExperiment)

set.seed(20241001)

sce <- scRNAseq::HermannSpermatogenesisData()
sce <- sce[, 1:300]

sce <- scuttle::logNormCounts(sce, assay.type = "spliced")
dec <- scran::modelGeneVar(sce)
top_genes <- scran::getTopHVGs(dec, n = 2000)
sce <- sce[top_genes, ]

sce <- RunPCA(sce, subset_row = top_genes, layer = "logcounts")
sce <- FindNeighbors(sce, dims = 1:20)
sce <- FindClusters(sce)
sce$cluster <- as.character(SingleCellExperiment::colLabels(sce))
sce <- RunUMAP(sce, dims = 1:20)

metadata(sce)$sclet_bookdown_cache <- list(
    source = "scRNAseq::HermannSpermatogenesisData",
    top_genes = top_genes,
    created_at = Sys.time()
)

dir.create("../data", showWarnings = FALSE)
saveRDS(sce, "../data/hermann-sperm-velo.rds")
